server:
  port: 8081
  #server.error.whitelabel.enabled=false
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_batch
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL5Dialect
    defer-datasource-initialization: true
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  batch:
    jdbc:
      initialize-schema: always
      isolation-level-for-create: serializable
      table-prefix: BATCH_

    job:
      enabled: false
      name: importEmployees

  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  jackson:
    serialization:
      fail-on-empty-beans: false
  sql:
    init:
      mode: always